qsub ./scripts/condi-seg/hpc.02-0.baselineUsingRegInc2_cv0.sh
qsub ./scripts/condi-seg/hpc.02-1.baselineUsingRegInc2_cv1.sh
qsub ./scripts/condi-seg/hpc.02-2.baselineUsingRegInc2_cv2.sh
qsub ./scripts/condi-seg/hpc.02-3.baselineUsingRegInc2_cv3.sh
qsub ./scripts/condi-seg/hpc.02-4.baselineUsingRegInc2_cv4.sh
qsub ./scripts/condi-seg/hpc.02-5.baselineUsingRegInc2_cv5.sh
qsub ./scripts/condi-seg/hpc.02-6.baselineUsingRegInc2_cv6.sh
qsub ./scripts/condi-seg/hpc.02-7.baselineUsingRegInc2_cv7.sh
qsub ./scripts/condi-seg/hpc.03-0.baselineUsingRegInc3_cv0.sh
qsub ./scripts/condi-seg/hpc.03-1.baselineUsingRegInc3_cv1.sh
qsub ./scripts/condi-seg/hpc.03-2.baselineUsingRegInc3_cv2.sh
qsub ./scripts/condi-seg/hpc.03-3.baselineUsingRegInc3_cv3.sh
qsub ./scripts/condi-seg/hpc.03-4.baselineUsingRegInc3_cv4.sh
qsub ./scripts/condi-seg/hpc.03-5.baselineUsingRegInc3_cv5.sh
qsub ./scripts/condi-seg/hpc.03-6.baselineUsingRegInc3_cv6.sh
qsub ./scripts/condi-seg/hpc.03-7.baselineUsingRegInc3_cv7.sh

qsub ./scripts/condi-seg/hpc.05-0.segModCbct_cv0.sh
qsub ./scripts/condi-seg/hpc.05-1.segModCbct_cv1.sh
qsub ./scripts/condi-seg/hpc.05-2.segModCbct_cv2.sh
qsub ./scripts/condi-seg/hpc.05-3.segModCbct_cv3.sh
qsub ./scripts/condi-seg/hpc.05-4.segModCbct_cv4.sh
qsub ./scripts/condi-seg/hpc.05-5.segModCbct_cv5.sh
qsub ./scripts/condi-seg/hpc.05-6.segModCbct_cv6.sh
qsub ./scripts/condi-seg/hpc.05-7.segModCbct_cv7.sh

qsub ./scripts/condi-seg/hpc.07-0.segModBoth_cv0.sh
qsub ./scripts/condi-seg/hpc.07-1.segModBoth_cv1.sh
qsub ./scripts/condi-seg/hpc.07-2.segModBoth_cv2.sh
qsub ./scripts/condi-seg/hpc.07-3.segModBoth_cv3.sh
qsub ./scripts/condi-seg/hpc.07-4.segModBoth_cv4.sh
qsub ./scripts/condi-seg/hpc.07-5.segModBoth_cv5.sh
qsub ./scripts/condi-seg/hpc.07-6.segModBoth_cv6.sh
qsub ./scripts/condi-seg/hpc.07-7.segModBoth_cv7.sh

qsub ./scripts/condi-seg/hpc.01-0.baseline_cv0.sh
qsub ./scripts/condi-seg/hpc.01-1.baseline_cv1.sh
qsub ./scripts/condi-seg/hpc.01-2.baseline_cv2.sh
qsub ./scripts/condi-seg/hpc.01-3.baseline_cv3.sh
qsub ./scripts/condi-seg/hpc.01-4.baseline_cv4.sh
qsub ./scripts/condi-seg/hpc.01-5.baseline_cv5.sh
qsub ./scripts/condi-seg/hpc.01-6.baseline_cv6.sh
qsub ./scripts/condi-seg/hpc.01-7.baseline_cv7.sh

qsub ./scripts/condi-seg/hpc.06-0.segModOneof_cv0.sh
qsub ./scripts/condi-seg/hpc.06-1.segModOneof_cv1.sh
qsub ./scripts/condi-seg/hpc.06-2.segModOneof_cv2.sh
qsub ./scripts/condi-seg/hpc.06-3.segModOneof_cv3.sh
qsub ./scripts/condi-seg/hpc.06-4.segModOneof_cv4.sh
qsub ./scripts/condi-seg/hpc.06-5.segModOneof_cv5.sh
qsub ./scripts/condi-seg/hpc.06-6.segModOneof_cv6.sh
qsub ./scripts/condi-seg/hpc.06-7.segModOneof_cv7.sh
qsub ./scripts/condi-seg/hpc.04-0.segModCt_cv0.sh
qsub ./scripts/condi-seg/hpc.04-1.segModCt_cv1.sh
qsub ./scripts/condi-seg/hpc.04-2.segModCt_cv2.sh
qsub ./scripts/condi-seg/hpc.04-3.segModCt_cv3.sh
qsub ./scripts/condi-seg/hpc.04-4.segModCt_cv4.sh
qsub ./scripts/condi-seg/hpc.04-5.segModCt_cv5.sh
qsub ./scripts/condi-seg/hpc.04-6.segModCt_cv6.sh
qsub ./scripts/condi-seg/hpc.04-7.segModCt_cv7.sh